AWS_REGION = "ap-south-1"
credentials_profile_name = "insurance-dev"
account = "insurance"
environment = "dev"
vpc_cidr = "10.111.0.0/16"
azs = ["ap-south-1a", "ap-south-1b", "ap-south-1c"]
cluster_version = 1.28
central_account_cidr = "10.200.0.0/16"
pem_key = "master-gromo-insure"
hosted_zone = "gromoinsure.in"
private_hosted_zone_enabled = false
route_53_credential_profile = "insurance-dev"